/// <summary>
/// 模块调用消息定义 >= 1000
/// 格式说明:模块名称_函数名称 = XXX, 首字母大写，最好加上函数参数说明
/// 每个模块id占用必须都是1000的整数倍
/// 例如 Game_Start = 1000,
/// </summary>
export enum ListenID {
    _Start = 999,
    // ----  登录系统
    Login_Start,
    Login_Finish,
    Login_User,
    Alert_TipsShow,
    Fight_BulletFinish,
    Fight_RecycleBullet,
    Fight_RecycleMonster,
    Fight_RecycleTool,
    Fight_RecycleBomb,
    Fight_RoleMove,         //人物移动
    Fight_RoleStand,        //人物站立
    Fight_MonAttack,
    Fight_SHOWEFFECT,
    Fight_SHOWEFFECT_NUM,
    Fight_Start,
    Fight_Pause,
    Fight_End,
    Fight_Restart,
    Fight_ShowGuide,
    Fight_AddTool,
    Fight_KillNumChange,    //击杀数量变化
    Fight_MonsterWarn,
    Fight_ReliveSuccess,
    Fight_StartNextStep,
    Fight_ChangeGun,
    Fight_GunUpdate,
    Fight_GunCD,
    Fight_ShowFlyGold,
    Fight_ShowImproveUI,
    Fight_Result,           //结算
    Fight_BloodWarn,
    Fight_ShowBuffUI,
    Fight_ShowShake,
    Fight_QTE_STOP,
    Fight_RecycleObj,
    Fight_QTE_STATE,
    Fight_ShowNomalTips,
    Fight_StartQte,
    Fight_ShowBossBlood,
    Fight_MonsterInfoList,
    Fight_KeepBoss,
    Fight_DownTime,
    Fight_DownTimeFinish,
    Fight_AddEquipDrop,
    Fight_OpenUnLockChapterView,
    Fight_UpdateStep,
    Fight_GetGold,
    Fight_GetExpAnimation,
    Fight_StartNextAfterAnim,
    FightToBoss,
    Fight_AddSkill,
    Fight_ShowBossWarn,
    Fight_TryEquip,
    Fight_TryEquipUpdate,
    Fight_SaveLocalChapterInfo,
    Game_UpdatePower,
    Game_UpdateGold,
    Game_FightBackToHome,
    Game_UpdateDiamond,
    Game_SetCurrencyVis,
    Game_UpdateCurrencyEffect,
    Game_RefreshTime,
    Game_OpenUIList,
    GetRewardClose,
    Setting_MuteMusic,
    Setting_MuteAudio,
    Setting_BlockShake,
    Setting_HurtShow,
    Setting_Open,
    Setting_Open_IOS,
    Shop_Open,
    Shop_Close,
    Shop_SelectItem,
    Shop_UnLock,
    Shop_ShowDetail,
    MoreGold_Open,
    Group_UpdateSelected,
    BtnMore_Open,
    Draw_AnimEnd,           //抽奖结束
    Show_WeaponUpgrade,
    Change_Weapon,
    GoldEffect_Show,
    GoldEffect_End,
    Update_GoldRewardNum,
    Result_BackHome,        //结算页返回主界面
    Menu_Login,             //进入主界面并且已登录
    Menu_Open,
    Menu_Collect,
    Menu_CloseMainView,
    Menu_OpenMainView,
    Menu_SelectChapter,
    Menu_ShowAnnounce,
    Menu_AnnounceClick,
    UnlockNewWeapon,
    Close_MoreGoldPanel,
    Close_InviteAndService,
    Close_FreeWeapon,
    Show_GoldUpgrade,
    Show_PlayerUpgrade,
    Show_WeaponLight,
    Guide_RigisterNodeTag,
    GroupView_Open,
    NoPower,
    Stop_CountDown,
    Resume_CountDown,
    Life_On_Show,
    Life_On_Hide,
    GetInviteReward,
    SecondDay,          //第二天
    Guide_Step1_Compelete,
    ShowBanner,
    HideBanner,
    ClickBanner,
    Servive_Close,
    Invite_Close,
    TipsLoading_Show,
    TipsLoading_Hide,
    checkGun,
    IAPSuccess,     //内购成功
    GetShareTimes,
    Refresh_ShareTimes,
    Show_WeaponLockNode,
    Close_SurpassFriendView,
    Close_GetDiamondPanel,
    GetSignReward,
    Refresh_InviteWeaponNum,
    IAPSuccessAndConfirm,
    VerIAPOrder,
    MainDrawEnd,//主界面抽奖结束
    MainDraw_GetEquip,
    RewardWelfare,
    Refresh_Point,
    ShowBossRank,
    Boss_CloseBossRank,
    Boss_OpenAlert,
    Boss_FightEnd,
    Open_TreasureBox,
    Refresh_Select,
    Refresh_Canopen,
    Shop_OpenBox,
    Rigister_Remind,
    Hide_InviteWeaponIcon,
    Shop_Box_Video_Success,
    Relive_Video_Success,
    Free_Weapon_Video_Success,
    Main_Draw_Video_Success,
    Result_Draw_Video_Success,
    Result_Reward_Video_Success,
    Sign_Welfare_Video_Success,
    Time_Gold_Video_Success,
    Bubble_Weapon_Video_Success,
    Role_Level_Up,
    Role_Baoji_Up,
    Role_Speed_Up,
    Role_Power_Up,
    Role_TimeGold_Up,
    Role_KillGold_Up,
    Role_HoldsEquip,
    Role_BattleChange,
    Map_addMapBgSuccess,
    Map_addMapDecorateSuccess,
    Scene_StartLoadMap,
    Equip_OpenDropPreView,//装备
    Equip_OpenEquipView,//装备界面
    Equip_CloseEquipView,
    Equip_OpenTipsView, //装备tips打开
    Equip_CloseTipsView,//装备Tips关闭
    Equip_OpenIntensifyView,
    Equip_StrengthUpdate,
    Equip_PropertyChange,
    Equip_ShowBattleTips,
    Equip_CloseEquipIntenView,
    Equip_CloseEquipSmeltView,
    Equip_OpenEquipSmeltView,
    Equip_SetEquipIsLock,
    Equip_OpenUnLockPartView,
    Equip_OpenPropertyView,
    Bag_AddItem,//背包道具变化
    Bag_RemoveItem,
    Log_Event,//宝箱
    Box_OpenBoxView,
    Box_UpdateBoxView,
    Box_RefreshFreeTime,
    Box_OpenBoxOpenView,
    Box_BoxOpenViewIsClose,
    Pay_CallBack,
    Pay_Finish,
    Box_CheckRepairPay,
    Box_OpenDirectPayView,
    Drop_InitDropPoolById,//d掉落
    Offline_RecoverDown,
    Rigister_FunUnlock,
    On_Open_Menu,
    On_Close_Menu,
    On_FunUnlock,
    On_Open_SmeltView,
    On_Close_SmeltView,
    On_Open_Upgrade,
    On_Close_Upgrade,
    UI_Close,
    Close_Guide,
    Person_OpenCreateView,//个人信息
    Person_OpenView,
    Person_OpenOtherInfoView,
    Rank_showRank,//排行榜
    Rank_closeRank,
    Announce_LogStartNum,//滚动公告
    Announce_AddMessage,
    MainDrawClose,
    RewardTask_OpenMainView,//悬赏任务
    RewardTask_CloseMainView,
    RewardTask_RefreshDailyTaskFinish,
    RewardTask_RefreshDailyTask,
    RewardTask_UpdateTaskProgress,
    RewardTask_OnReward,
    RewardTask_ToGetReward,

    SKillTips_Open,
    Skill_OpenSelectView,//skill
    Skill_OpenConfirmView,

    Role_GetExp,
    Role_CostPower,
    Event_OpenView,//event

    Technoloty_OpenView,
    Technoloty_CloseView,
    Open_EcologicalView,
    Close_EcologicalView,
    Open_EcologicalRewardView,

    TechnologyPoint_Change,
    TechnologyLevel_Change,

    Guide_Check_Condition,

    Sign_Double,
}


